[workspace]
resolver = "2"
members = [
    "crates/sudohand-core",
    "crates/sudohand-desktop",
    "crates/sudohand-browser",
    "crates/sudohand-fs",
    "crates/sudohand-shell",
    "sudohand-cli",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/joezhoujinjing/sudohand"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
sudohand-core = { path = "crates/sudohand-core" }
sudohand-desktop = { path = "crates/sudohand-desktop" }
sudohand-browser = { path = "crates/sudohand-browser" }
sudohand-fs = { path = "crates/sudohand-fs" }
sudohand-shell = { path = "crates/sudohand-shell" }

[profile.release]
strip = true
