//! Reference fixture generated by ai-dev-browser 94170d23's public PoolState API.
use serde_json::{json, Value};
use sudohand_browser::pool::{load_state, save_state, Job, JobResult, JobStatus, PoolState};
use sudohand_browser::pool::{ProfileManager, ProfileMode};
use sudohand_browser::pool::{Worker, WorkerStatus};

#[test]
fn worker_status_matches_python_snapshot() {
    let mut worker = Worker::new(3, 9353);
    assert_eq!(worker.stats.success_rate(), 0.0);
    let mut job = Job::new("fetch");
    job.job_id = "active".into();
    worker.current_job = Some(job);
    worker.status = WorkerStatus::Busy;
    worker.stats.success = 2;
    worker.stats.fail = 1;
    worker.stats.total_time = 12.5;
    let reference: Value = serde_json::from_str(include_str!("fixtures/pool-worker.json")).unwrap();
    assert_eq!(worker.to_dict(), reference);
}

#[test]
fn cookie_profile_modes() {
    let dir = tempfile::tempdir().unwrap();
    let file = dir.path().join("shared/cookies.dat");
    let workers = dir.path().join("workers");
    let make = |mode| ProfileManager::new(mode, Some(file.clone()), Some(workers.clone())).unwrap();
    let temp = make(ProfileMode::Temp);
    assert_eq!(temp.get_cookies_file(0), None);
    assert!(!file.parent().unwrap().exists());
    assert!(!workers.exists());
    let shared = make(ProfileMode::Shared);
    assert_eq!(shared.get_cookies_file(0), Some(file.clone()));
    assert_eq!(shared.get_cookies_file(1), Some(file.clone()));
    assert!(file.parent().unwrap().is_dir());
    assert!(!file.exists());
    let per_worker = make(ProfileMode::PerWorker);
    assert_eq!(
        per_worker.get_cookies_file(2),
        Some(workers.join("cookies_worker_2.dat"))
    );
    assert_eq!(
        per_worker.get_cookies_file(3),
        Some(workers.join("cookies_worker_3.dat"))
    );
    assert!(workers.is_dir());
}

#[test]
fn python_snapshot_roundtrip_and_recovery() {
    let source = include_str!("fixtures/pool-state-v1.json");
    let mut state: PoolState = serde_json::from_str(source).unwrap();
    assert_eq!(
        serde_json::to_value(&state).unwrap(),
        serde_json::from_str::<Value>(source).unwrap()
    );
    let failure = &state.completed["failed"];
    assert_eq!(failure.error_type.as_deref(), Some("TimeoutError"));
    assert_eq!(
        failure.error_bases,
        ["OSError", "Exception", "BaseException"]
    );
    // BrowserPool.save_state in Python can list the same job twice.
    state.pending.push(state.in_progress[0].clone());
    state.resume();
    assert!(state.in_progress.is_empty());
    assert_eq!(
        state
            .pending
            .iter()
            .map(|j| j.job_id.as_str())
            .collect::<Vec<_>>(),
        ["pending", "interrupted"]
    );
    assert_eq!(state.pending[1].retries, 2);
    assert!(state.pending.iter().all(|j| j.status == JobStatus::Pending));
    assert_eq!(state.completed.len(), 2);
    let resumed = state.clone();
    state.resume();
    assert_eq!(state, resumed);
}

#[test]
fn atomic_overwrite_and_malformed_state() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("nested/state.json");
    assert!(load_state(&path).unwrap().is_none());
    let mut state = PoolState::default();
    let job = Job::new("fetch");
    state.pending.push(job.clone());
    save_state(&mut state, &path).unwrap();
    assert_eq!(load_state(&path).unwrap().unwrap(), state);
    state.pending.clear();
    state.completed.insert(
        job.job_id.clone(),
        JobResult::success(&job.job_id, json!({"ok":true}), Some(1)),
    );
    save_state(&mut state, &path).unwrap();
    assert_eq!(load_state(&path).unwrap().unwrap(), state);
    assert_eq!(
        std::fs::read_dir(path.parent().unwrap()).unwrap().count(),
        1
    );
    for invalid in ["{", "{}", r#"{"last_updated":"invalid timestamp"}"#] {
        std::fs::write(&path, invalid).unwrap();
        assert!(load_state(&path).unwrap().is_none());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), invalid);
    }
}

#[test]
fn retry_budget_and_failure_identity() {
    let mut job = Job::new("fetch");
    job.retries = 500;
    assert!(job.can_retry());
    job.max_retries = 2;
    job.retries = 1;
    assert!(job.can_retry());
    job.retries = 2;
    assert!(!job.can_retry());
    let result = JobResult::failure(
        &job.job_id,
        "blocked",
        "RateLimit",
        vec!["Transient".into()],
        Some(3),
    );
    let restored: JobResult =
        serde_json::from_value(serde_json::to_value(&result).unwrap()).unwrap();
    assert_eq!(restored, result);
    assert!(!result.success);
    assert_eq!(result.error_type.as_deref(), Some("RateLimit"));
    let mut legacy = serde_json::to_value(&result).unwrap();
    legacy["error_bases"] = Value::Null;
    assert!(serde_json::from_value::<JobResult>(legacy)
        .unwrap()
        .error_bases
        .is_empty());
}
