//! The fixture is regenerated by scripts/pool_parity.py from the running Python
//! scheduler in CI. The Rust scheduler must produce the same observable trace.
use serde_json::{json, Map, Value};
use std::{
    collections::BTreeMap,
    sync::{Arc, Mutex},
    time::Duration,
};
use sudohand_browser::{pool::*, Result};

#[derive(Default)]
struct Trace {
    calls: Vec<Value>,
    closed: usize,
}
struct FixtureClient {
    trace: Arc<Mutex<Trace>>,
    attempts: BTreeMap<String, usize>,
}
impl PoolClient for FixtureClient {
    fn execute<'a>(
        &'a mut self,
        job: &'a Job,
        _context: JobContext,
    ) -> PoolFuture<'a, std::result::Result<ExecutionResult, JobFailure>> {
        Box::pin(async move {
            let label = job.args[0].as_str().unwrap();
            let attempt = self.attempts.entry(label.into()).or_default();
            *attempt += 1;
            self.trace
                .lock()
                .unwrap()
                .calls
                .push(json!([label, *attempt]));
            if label == "terminal" || (label == "retry" && *attempt < 3) {
                return Err(JobFailure {
                    message: label.into(),
                    error_type: Some("FixtureError".into()),
                    error_bases: vec!["Exception".into(), "BaseException".into()],
                });
            }
            if label == "business" {
                return Ok(ExecutionResult {
                    data: json!({"label":"business", "success":false}),
                    success: false,
                });
            }
            Ok(json!({"label":label, "attempt":*attempt}).into())
        })
    }
    fn close(&mut self, close_browser: bool) -> PoolFuture<'_, Result<()>> {
        Box::pin(async move {
            assert!(!close_browser);
            self.trace.lock().unwrap().closed += 1;
            Ok(())
        })
    }
}

#[tokio::test]
async fn scheduler_matches_running_python_contract() {
    let fixtures: Vec<Value> =
        serde_json::from_str(include_str!("fixtures/pool-scheduler.json")).unwrap();
    for fixture in fixtures {
        let trace = Arc::new(Mutex::new(Trace::default()));
        let factory: ClientFactory = {
            let trace = trace.clone();
            Arc::new(move |options| {
                assert!(options.port > 0 && options.headless && options.cookies_file.is_none());
                let client = FixtureClient {
                    trace: trace.clone(),
                    attempts: BTreeMap::new(),
                };
                Box::pin(async move { Ok(Box::new(client) as Box<dyn PoolClient>) })
            })
        };
        let budget = i32::try_from(fixture["budget"].as_i64().unwrap()).unwrap();
        let position = fixture["position"].as_str().unwrap();
        let pool = BrowserPool::start(
            factory,
            PoolOptions {
                workers: 1,
                max_retries: budget,
                headless: true,
                close_browsers: false,
                profile: ProfileMode::Temp,
                requeue_position: if position == "front" {
                    RequeuePosition::Front
                } else {
                    RequeuePosition::Back
                },
                ..PoolOptions::default()
            },
        )
        .await
        .unwrap();
        let mut labels = vec!["retry", "ok", "business"];
        if budget != -1 {
            labels.push("terminal");
        }
        let ids: Vec<_> = labels
            .iter()
            .map(|label| {
                pool.run("perform", vec![json!(label)], Map::new(), None, true)
                    .unwrap()
            })
            .collect();
        let results = pool
            .wait(Some(&ids), None, Some(Duration::from_secs(5)))
            .await
            .unwrap();
        let outcomes: Map<String, Value> = labels
            .iter()
            .zip(&ids)
            .map(|(label, id)| {
                let result = &results[id];
                (
                    label.to_string(),
                    json!({"success":result.success, "data":result.data,
                "error":result.error, "error_type":result.error_type,
                "error_bases":result.error_bases, "worker_id":result.worker_id}),
                )
            })
            .collect();
        let stats = &pool.worker_stats()[&0];
        let statistics = json!({"success":stats.success,"fail":stats.fail,"total":stats.total()});
        pool.shutdown(true).await.unwrap();
        let trace = trace.lock().unwrap();
        let actual = json!({"position":position,"budget":budget,"calls":trace.calls,
            "results":outcomes,"stats":statistics,"closed":trace.closed});
        assert_eq!(actual, fixture, "policy={position} budget={budget}");
    }
}
